/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ScheduleRouteRouteImport } from './routes/schedule/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ContactRouteRouteImport } from './routes/contact/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as TicketsUserIdRouteImport } from './routes/tickets/$userId'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardUnregisteredRouteImport } from './routes/dashboard/unregistered'
import { Route as DashboardTemplateEditorRouteImport } from './routes/dashboard/template-editor'
import { Route as DashboardRegisteredRouteImport } from './routes/dashboard/registered'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardImportErrorsRouteImport } from './routes/dashboard/import-errors'
import { Route as DashboardBranchesRouteImport } from './routes/dashboard/branches'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRouteRoute = ScheduleRouteRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRouteRoute = ContactRouteRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScheduleRouteRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactRouteRoute,
} as any)
const TicketsUserIdRoute = TicketsUserIdRouteImport.update({
  id: '/tickets/$userId',
  path: '/tickets/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUnregisteredRoute = DashboardUnregisteredRouteImport.update({
  id: '/unregistered',
  path: '/unregistered',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplateEditorRoute = DashboardTemplateEditorRouteImport.update({
  id: '/template-editor',
  path: '/template-editor',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRegisteredRoute = DashboardRegisteredRouteImport.update({
  id: '/registered',
  path: '/registered',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportErrorsRoute = DashboardImportErrorsRouteImport.update({
  id: '/import-errors',
  path: '/import-errors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBranchesRoute = DashboardBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/import-errors': typeof DashboardImportErrorsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/registered': typeof DashboardRegisteredRoute
  '/dashboard/template-editor': typeof DashboardTemplateEditorRoute
  '/dashboard/unregistered': typeof DashboardUnregisteredRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/tickets/$userId': typeof TicketsUserIdRoute
  '/contact/': typeof ContactIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/import-errors': typeof DashboardImportErrorsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/registered': typeof DashboardRegisteredRoute
  '/dashboard/template-editor': typeof DashboardTemplateEditorRoute
  '/dashboard/unregistered': typeof DashboardUnregisteredRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/tickets/$userId': typeof TicketsUserIdRoute
  '/contact': typeof ContactIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/register': typeof RegisterIndexRoute
  '/schedule': typeof ScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/import-errors': typeof DashboardImportErrorsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/registered': typeof DashboardRegisteredRoute
  '/dashboard/template-editor': typeof DashboardTemplateEditorRoute
  '/dashboard/unregistered': typeof DashboardUnregisteredRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/tickets/$userId': typeof TicketsUserIdRoute
  '/contact/': typeof ContactIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/register'
    | '/schedule'
    | '/callback'
    | '/signin'
    | '/dashboard/branches'
    | '/dashboard/import-errors'
    | '/dashboard/messages'
    | '/dashboard/registered'
    | '/dashboard/template-editor'
    | '/dashboard/unregistered'
    | '/dashboard/users'
    | '/tickets/$userId'
    | '/contact/'
    | '/dashboard/'
    | '/register/'
    | '/schedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/signin'
    | '/dashboard/branches'
    | '/dashboard/import-errors'
    | '/dashboard/messages'
    | '/dashboard/registered'
    | '/dashboard/template-editor'
    | '/dashboard/unregistered'
    | '/dashboard/users'
    | '/tickets/$userId'
    | '/contact'
    | '/dashboard'
    | '/register'
    | '/schedule'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/register'
    | '/schedule'
    | '/callback'
    | '/signin'
    | '/dashboard/branches'
    | '/dashboard/import-errors'
    | '/dashboard/messages'
    | '/dashboard/registered'
    | '/dashboard/template-editor'
    | '/dashboard/unregistered'
    | '/dashboard/users'
    | '/tickets/$userId'
    | '/contact/'
    | '/dashboard/'
    | '/register/'
    | '/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRouteRoute: typeof ContactRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  ScheduleRouteRoute: typeof ScheduleRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  SigninRoute: typeof SigninRoute
  TicketsUserIdRoute: typeof TicketsUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof ContactRouteRoute
    }
    '/tickets/$userId': {
      id: '/tickets/$userId'
      path: '/tickets/$userId'
      fullPath: '/tickets/$userId'
      preLoaderRoute: typeof TicketsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/unregistered': {
      id: '/dashboard/unregistered'
      path: '/unregistered'
      fullPath: '/dashboard/unregistered'
      preLoaderRoute: typeof DashboardUnregisteredRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/template-editor': {
      id: '/dashboard/template-editor'
      path: '/template-editor'
      fullPath: '/dashboard/template-editor'
      preLoaderRoute: typeof DashboardTemplateEditorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/registered': {
      id: '/dashboard/registered'
      path: '/registered'
      fullPath: '/dashboard/registered'
      preLoaderRoute: typeof DashboardRegisteredRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import-errors': {
      id: '/dashboard/import-errors'
      path: '/import-errors'
      fullPath: '/dashboard/import-errors'
      preLoaderRoute: typeof DashboardImportErrorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/branches': {
      id: '/dashboard/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof DashboardBranchesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface ContactRouteRouteChildren {
  ContactIndexRoute: typeof ContactIndexRoute
}

const ContactRouteRouteChildren: ContactRouteRouteChildren = {
  ContactIndexRoute: ContactIndexRoute,
}

const ContactRouteRouteWithChildren = ContactRouteRoute._addFileChildren(
  ContactRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardBranchesRoute: typeof DashboardBranchesRoute
  DashboardImportErrorsRoute: typeof DashboardImportErrorsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardRegisteredRoute: typeof DashboardRegisteredRoute
  DashboardTemplateEditorRoute: typeof DashboardTemplateEditorRoute
  DashboardUnregisteredRoute: typeof DashboardUnregisteredRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBranchesRoute: DashboardBranchesRoute,
  DashboardImportErrorsRoute: DashboardImportErrorsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardRegisteredRoute: DashboardRegisteredRoute,
  DashboardTemplateEditorRoute: DashboardTemplateEditorRoute,
  DashboardUnregisteredRoute: DashboardUnregisteredRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface RegisterRouteRouteChildren {
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

interface ScheduleRouteRouteChildren {
  ScheduleIndexRoute: typeof ScheduleIndexRoute
}

const ScheduleRouteRouteChildren: ScheduleRouteRouteChildren = {
  ScheduleIndexRoute: ScheduleIndexRoute,
}

const ScheduleRouteRouteWithChildren = ScheduleRouteRoute._addFileChildren(
  ScheduleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRouteRoute: ContactRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  ScheduleRouteRoute: ScheduleRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  SigninRoute: SigninRoute,
  TicketsUserIdRoute: TicketsUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
